### ISSUE TITLE
Multiple speeds lead to overlap on the token.

### ISSUE THREAD

**Issue by git-kor-av** [jopeek/fvtt-token-info-icons#22] opened 2021-01-25 03:54 UTC
For example a black dragon has walking speed, swimming speed, and flying speed.  This is what it looks like when there are 3 speeds:
![token-info-icons-with-3-speeds](https://user-images.githubusercontent.com/32276185/105659520-e8df8480-5e96-11eb-8beb-1501439398c7.png)

This occurs on foundry 0.7.9, DnD5E 1.2.4, and Token Icon Info 2.2.1.

**Comment by jopeek** [comment] 2021-01-25 03:55
Hmm weird. They’re supposed to stack. I’ll check it out.

**Comment by jopeek** [comment] 2021-01-26 19:28
What browser are you using? In chrome/edge it stacks the speeds as intended.

**Comment by git-kor-av** [comment] 2021-01-26 21:36
I was using Firefox in this test.  I’ll double check it on Chrome as well.

**Comment by jopeek** [comment] 2021-01-26 21:40
Fair enough. Firefox doesn’t display it right. Hot fix incoming.

**Comment by jopeek** [comment] 2021-01-26 21:45
Fixed in 2.2.2.

**Closed as completed by jopeek** 2021-01-26 21:45 UTC
